### ISSUE TITLE
[Feature] 초기 세팅 구축

### ISSUE THREAD

**Issue by nakyeongg** [2024-likelion-sswu/Funit_FE#1]
## ✔️ Issue

프로젝트 초기 세팅을 구축합니다

## 📝 To-do

- [x] 폴더 구조 생성
- [x] 모바일 화면 구현
- [x] 스플래시 화면 구현
